doc/source/environments/index.rst, doc/source/index.rst, flygym/envs/nmf_mujoco.py, scripts/kin_replay.py, scripts/sine_wave.py, tests/test_mujoco.py
Closes #15. See Gym API specs here: https://gymnasium.farama.org/api/env/#gymnasium.Env.step
=> change .step()'s return signature to fully comply with Gym API specs

.gitignore, flygym/arena/__init__.py, flygym/arena/base.py, flygym/arena/mujoco_terrain.py, flygym/envs/nmf_mujoco.py, flygym/state/__init__.py, flygym/state/preprogrammed.py, flygym/state/state.py, flygym/tests/__init__.py, flygym/tests/common.py, flygym/tests/test_mujoco_arenas.py, flygym/tests/test_mujoco_basic.py, flygym/tests/test_mujoco_pose.py, flygym/tests/test_mujoco_worlds.py, flygym/util/config.py, scripts/kin_replay.py, scripts/sine_wave.py
This addresses #22 #30 #34.
Docs pending.
=> Separate pose, parameters, and arena into separate classes

flygym/arena/base.py, flygym/arena/mujoco_arena.py, flygym/envs/nmf_mujoco.py, flygym/tests/test_mujoco_odor.py, scripts/olfaction.py
=> Olfaction implementation

doc/source/installation.rst, notebooks/gym_basics_and_kinematic_replay.ipynb
Create notebooks/outputs because fig.savefig raises a FileNotFoundError if the parent directory of the figure does not exist.
No
=> create notebooks/outputs/ directory if it does not exist

doc/source/tutorials/cpg_controller.rst, notebooks/cpg_controller.ipynb, setup.py
Bug in adhesion on/off calculation: phase was not wrapped around 2pi.
This fix does not result in a new release because the change is only on the docs website.
=> Fix adhesion on/off bug in tutorial

README.md
Update README, no new release
NA
=> update README - no new release

README.md, doc/source/contributing.rst, doc/source/index.rst, flygym/mujoco/core.py, setup.py
=> Bump version to 0.2.3

doc/source/tutorials/turning.rst, flygym/mujoco/core.py, flygym/mujoco/examples/common.py, flygym/mujoco/examples/hybrid_turning_controller.py, flygym/mujoco/examples/turning_controller.py, notebooks/turning.ipynb
- Add turning tutorial
- Add metadata attribute to NeuroMechFly class as specified in the Gym API
N/A
=> Turning tutorial

.github/workflows/tests.yaml, doc/source/index.rst, doc/source/tutorials/olfaction.rst, flygym/mujoco/examples/olfaction.py, notebooks/olfaction.ipynb
=> Add olfaction tutorial

doc/source/changelog.rst, doc/source/index.rst, doc/source/tutorials/index.rst, doc/source/tutorials/rule_based_controller.rst, flygym/mujoco/arena/sensory_environment.py, setup.py
Fix MuJoCo version to 2.3.x as there are a few [API-breaking changes in 3.0.0](https://mujoco.readthedocs.io/en/3.0.0/changelog.html#general) released last week. Update docs.
N/A
=> Merge v0.2.4

doc/source/index.rst, doc/source/installation.rst, setup.py
Update docs, especially wrt info on rendering on platforms without displays (eg servers).
NA
=> Docs update — esp. rendering on platforms without displays

README.md, doc/source/conf.py
=> Add banner graphics

.github/workflows/documentation.yaml, doc/source/conf.py, doc/source/index.rst
Add Google analytics and associated disclaimer
=> Add Google analytics and associated disclaimer

flygym/mujoco/config.yaml
Just a very minor change to fix the "grey" Pedicel problem!
=> fix the duplicate LPedicel in config.yaml

.github/workflows/tests.yaml, README.md, doc/source/installation.rst, setup.py
=> add python 3.12 as a supported version

flygym/examples/head_stabilization/closed_loop_deployment.py, flygym/examples/head_stabilization/viz.py
Visualization: stabilizing the neck camera and plotting the neck control signal
=> Visualization: stabilizing the neck camera and plotting the neck control signal

doc/source/tutorials/advanced_olfaction.rst, doc/source/tutorials/advanced_vision.rst, doc/source/tutorials/head_stabilization.rst, doc/source/tutorials/index.rst, doc/source/tutorials/path_integration.rst, doc/source/tutorials/simple_olfaction.rst, doc/source/tutorials/simple_vision.rst
=> Add temporary pointers to new examples on website

.github/workflows/documentation.yaml, notebooks/hybrid_controller.ipynb, setup.py
=> Fix dependency for sphinx site building

.github/workflows/documentation.yaml, .github/workflows/tests.yaml, doc/source/gallery/index.rst, doc/source/gallery/video_10_odour_taxis.rst, doc/source/gallery/video_11_head_stabilization.rst, doc/source/gallery/video_12_multimodal_navigation.rst, doc/source/gallery/video_13_plume_navigation.rst, doc/source/gallery/video_14_fly_follow_fly.rst, doc/source/gallery/video_3_forces.rst, doc/source/gallery/video_4_climbing.rst, doc/source/gallery/video_8_controller_comparison.rst, doc/source/gallery/video_9_visual_taxis.rst, doc/source/index.rst
=> Gallery in website

flygym/camera.py
Fixes #185 but the logic is still quite complicated and require simplification. At some point we should discuss with @stimpfli  and simplify the camera logic.
#185
=> Fix following camera

flygym/examples/locomotion/README.md, flygym/examples/locomotion/controller_comparison.py
=> add controller comparison

.github/workflows/tests_linux.yaml, .github/workflows/tests_macos.yaml, .github/workflows/tests_windows.yaml, doc/source/installation.rst, flygym/__init__.py, flygym/examples/head_stabilization/collect_training_data.py, flygym/examples/head_stabilization/tests/test_model.py, flygym/examples/olfaction/simple_odor_taxis.py, flygym/examples/olfaction/tests/test_plume_tracking_task.py, flygym/examples/path_integration/exploration.py, flygym/examples/path_integration/tests/test_exploration.py, flygym/examples/path_integration/tests/test_integration.py, flygym/tests/test_arena.py, flygym/tests/test_basic.py, flygym/tests/test_check_env.py, flygym/tests/test_odor.py, flygym/tests/test_pose.py, flygym/tests/test_vision.py
Add CI checks for Windows and macOS, but skipping rendering because it's not trivial to get rendering to work on headless Windows/Mac servers, and I doubt many people are using Windows/Mac servers to run NeuroMechFly.
=> Add CI checks for Windows and macOS

.dockerignore, .github/workflows/tests_docker.yaml, Dockerfile, doc/source/installation.rst
Add dockerfile and CI to test it
=> add dockerfile and CI to test it

doc/source/tutorials/advanced_olfaction.rst, doc/source/tutorials/advanced_vision.rst, doc/source/tutorials/cpg_controller.rst, doc/source/tutorials/gym_basics_and_kinematic_replay.rst, doc/source/tutorials/head_stabilization.rst, doc/source/tutorials/hybrid_controller.rst, doc/source/tutorials/olfaction_basics.rst, doc/source/tutorials/path_integration.rst, doc/source/tutorials/rule_based_controller.rst, doc/source/tutorials/turning.rst, doc/source/tutorials/vision_basics.rst, setup.py
Minor improvement in tutorial display format.
=> Site formatting change

setup.py
This is a placeholder for the next release. Changes for v1.0.1(-pre.1) will be merged into `dev-v1.0.1-pre.1`.
N/A
=> Develop: dev-v1.0.1-pre.1

.github/workflows/tests_full.yaml, .github/workflows/tests_macos.yaml, .github/workflows/tests_ubuntu22.yaml, .github/workflows/tests_windows.yaml, flygym/data/pose/pose_stretch.yaml, flygym/data/pose/pose_zero.yaml, setup.py
Currently some leg DoFs are missing their joint angle values in the preprogrammed poses. This PR is a fix.
No but this is a continuation of #201
=> Fix missing DoFs in preset poses

doc/source/api_ref/mdp_specs.rst, doc/source/tutorials/advanced_olfaction.rst, doc/source/tutorials/path_integration.rst, doc/source/tutorials/turning.rst, doc/source/tutorials/vision_basics.rst, flygym/examples/head_stabilization/closed_loop_deployment.py, flygym/examples/locomotion/__init__.py, flygym/examples/locomotion/tests/test_hybrid_turning.py, flygym/examples/locomotion/turning_controller.py, flygym/examples/locomotion/turning_fly.py, notebooks/advanced_olfaction.ipynb, notebooks/path_integration.ipynb, notebooks/turning.ipynb, notebooks/vision_basics.ipynb
… and simplify some imports
Some stuff in the RST and text blocks of the IPYNB files are out of date after v1.0.0 refactoring. They escaped our/CI's attention because they are just texts. This PR aims to fix this issue. 
#207
=> Update out-of-date import paths in RST files and note books

flygym/vision/retina.py
Simplify visual calibration function
No
=> Simplify visual calibration function

doc/source/index.rst, doc/source/sfn2024.rst
Add sfn workshop info page on website
No
=> Add sfn workshop info page on website (no code change)

doc/source/sfn2024.rst
=> Fix register button color on workshop info page (no code change)

doc/source/sfn2024.rst
Update website to close NMF workshop registration
=> Close NMF workshop registration

flygym/fly.py, flygym/simulation.py
It should be a 3-tuple of floats, not a single float
https://mujoco.readthedocs.io/en/latest/XMLreference.html#body-geom
=> Fix some type annotation bugs

flygym/fly.py
=> Faster-vision-conversion
